uiy = 1 - uih;                                                            

ui_batch_switch = uicontrol(    'Parent', uitab_batch, 'Style', 'checkbox', 'Units', 'normalized', 'Value', 0, 'Enable', 'off',...
                                'String', t('Batch Mode (overrides the "Single/Through Zernike" mode)'),...
                                'FontSize', ui_figures.fontsize_text, 'Position', [uis uiy 1-2*uis uih]);

ui_batch_source = uicontrol(    'Parent', uitab_batch, 'Style', 'popup', 'Units', 'normalized',...
                                'String', dropdown_content, 'Position', [1-uis-1.8*uil uiy 1.8*uil 0.6*uih],...
                                'FontSize', 1.5*ui_figures.fontsize_text);
                                                                                               
uiy = uiy-0.5*uih-uis;
ui_batch_recalc =   uicontrol(  'Parent', uitab_batch, 'Style', 'checkbox', 'Units', 'normalized', 'Value', 0,...
                                'String', t('New Radius [mm]:'), 'Position', [uis uiy 1.7*uil 0.5*uih],...
                                'FontSize', ui_figures.fontsize_text);
ui_batch_radius =   uicontrol(  'Parent', uitab_batch, 'Style', 'edit', 'Units', 'normalized',...
                                'String', sprintf(['%',ui_defaults.float_precision,'f'], ui_defaults.pupil_radius), 'Position', [uis+1.7*uil uiy uil 0.6*uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_edit,...
                                'Callback', { @validate_double, ui_defaults.pupil_radius });
          
                    uicontrol(  'Parent', uitab_batch, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'right',...
                                'String', t('Device Lambda [nm]:'), 'Position', [1-2*uis-2.8*uil uiy-0.3*uih 1.8*uil uih-uis],...
                                'FontSize', ui_figures.fontsize_text);
ui_batch_lambda =  uicontrol(   'Parent', uitab_batch, 'Style', 'edit', 'Units', 'normalized',...
                                'String', sprintf(['%',ui_defaults.float_precision,'f'], ui_defaults.reference_lambda), 'Position', [1-uis-uil uiy uil 0.6*uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_edit,...
                                'Callback', { @validate_double, ui_defaults.reference_lambda });
                            
set(ui_batch_source, 'Callback', { @setup_device_ui, ui_batch_lambda });
                            
uiy = uiy-1.5*uih-uis;
                    uicontrol(  'Parent', uitab_batch, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'left',...
                                'String', t('This panel allows you to load multiple eyes at once and process them one by one as if they were a through-focus simulation. Each file is verified before you can start the analyses.'),...
                                'Position', [uis uiy-uis 1-2*uis 2*uih-uis],...
                                'FontSize', ui_figures.fontsize_text);
                            
ui_batch_files =    uipanel(    'Parent', uitab_batch, 'Title', t('Files to process (in order)'),...
                                'Units', 'normalized', 'FontSize', ui_figures.fontsize_panel,...
                                'Position', [uis 0.15 1-2*uis uiy-uis-0.10], 'BackgroundColor', ui_figures.bg_figure);
ui_batch_filelist = uicontrol(  'Parent', ui_batch_files, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'left',...
                                'String', '', 'Position', [uis uis 1-2*uis 1-2*uis],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_figure);
                            
set(ui_batch_filelist, 'String', t('Click on "Load Batch" and select all of the files you want to process. Then, tick the "Batch Mode" box and finally start the desired analysis.'));
set(ui_batch_filelist, 'FontName', 'FixedWidth');

icon = imread('zernike_import.png');
                    uicontrol(  'Parent', uitab_batch, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'center',...
                                'String', t('Import'), 'Position', [uis 2*uis+0.6*uih 0.10 0.5*uih],...
                                'FontSize', ui_figures.fontsize_text);
ui_batch_import =    uicontrol( 'Parent', uitab_batch, 'Style', 'PushButton', 'Units', 'normalized', 'HorizontalAlignment', 'right',...
                                'String', '', 'cdata', icon, 'Position', [uis uis 0.10 uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_green);