uiy = 1-uih;

                    uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'left',...
                                'String', t('Sphere [D]:'), 'Position', [uis uiy-0.3*uih 2*uil uih-uis],...
                                'FontSize', ui_figures.fontsize_text);   
ui_rx_sphere =      uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'edit', 'Units', 'normalized',...
                                'String', '', 'Enable', 'inactive', 'Tag', 'readonly', 'Position', [2*(uis+uil) uiy 0.75*uil 0.7*uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_edit);
                            
                    uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'left',...
                                'String', t('RMS Error [um]:'), 'Position', [3.5*(uis+uil) uiy-0.3*uih 2*uil uih-uis],...
                                'FontSize', ui_figures.fontsize_text);
ui_wavefront_rms =  uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'edit', 'Units', 'normalized',...
                                'String', '', 'Enable', 'inactive', 'Tag', 'readonly', 'Position', [5.3*(uis+uil) uiy 0.75*uil 0.7*uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_edit);
                            
uiy = uiy - 0.5*uih - uis;

                    uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'left',...
                                'String', t('Cylinder [D]:'), 'Position', [uis uiy-0.3*uih 2*uil uih-uis],...
                                'FontSize', ui_figures.fontsize_text);
ui_rx_cylinder=     uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'edit', 'Units', 'normalized',...
                                'String', '', 'Enable', 'inactive', 'Tag', 'readonly', 'Position', [2*(uis+uil) uiy 0.75*uil 0.7*uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_edit);
                            
                    uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'left',...
                                'String', t('Axis [deg]:'),  'Position', [3.5*(uis+uil) uiy-0.3*uih 2*uil uih-uis],...
                                'FontSize', ui_figures.fontsize_text);
ui_rx_cylinder_axis=uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'edit', 'Units', 'normalized',...
                                'String', '', 'Enable', 'inactive', 'Tag', 'readonly', 'Position', [5.3*(uis+uil) uiy 0.75*uil 0.7*uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_edit);                                                  
uiy = uiy - 0.5*uih - uis;

                   uicontrol(   'Parent', uitab_ophtalmic, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'left',...
                                'String', t('Coma [D/mm]:'),               'Position', [uis uiy-0.3*uih 2*uil uih-uis],...
                                'FontSize', ui_figures.fontsize_text);
ui_rx_coma =       uicontrol(   'Parent', uitab_ophtalmic, 'Style', 'edit', 'Units', 'normalized',...
                                'String', '', 'Enable', 'inactive', 'Tag', 'readonly', 'Position', [2*(uis+uil) uiy 0.75*uil 0.7*uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_edit);
                            
                   uicontrol(   'Parent', uitab_ophtalmic, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'left',...
                                'String', t('Axis [deg]:'), 'Position', [3.5*(uis+uil) uiy-0.3*uih 2*uil uih-uis],...
                                'FontSize', ui_figures.fontsize_text);
ui_rx_coma_axis =  uicontrol(   'Parent', uitab_ophtalmic, 'Style', 'edit', 'Units', 'normalized',...
                                'String', '', 'Enable', 'inactive', 'Tag', 'readonly', 'Position', [5.3*(uis+uil) uiy 0.75*uil 0.7*uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_edit);                            
uiy = uiy - 0.5*uih - uis;

                    uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'left',...
                                'String', t('Spherical Aberration [D/mm2]:'), 'Position', [uis uiy-0.3*uih 2*uil uih-uis],...
                                'FontSize', ui_figures.fontsize_text);
ui_rx_spherical=    uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'edit', 'Units', 'normalized',...
                                'String', '', 'Enable', 'inactive', 'Tag', 'readonly', 'Position', [2*(uis+uil) uiy 0.75*uil 0.7*uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_edit);   
                            
uiy = uiy - 0.5*uih - uis;
                    uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'left',...
                                'String', t('Spherical Equivalent [D]:'),  'Position', [uis uiy-0.3*uih 2*uil uih-uis],...
                                'FontSize', ui_figures.fontsize_text);
ui_rx_spherical_eq= uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'edit', 'Units', 'normalized',...
                                'String', '', 'Enable', 'inactive', 'Tag', 'readonly', 'Position', [2*(uis+uil) uiy 0.75*uil 0.7*uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_edit);
                    uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'left',...
                                'String', t('MTR Spherical Equiv. [D]:'), 'Position', [3.5*(uis+uil) uiy-0.3*uih 2*uil uih-uis],...
                                'FontSize', ui_figures.fontsize_text);
ui_rx_mtr_eq =      uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'edit', 'Units', 'normalized',...
                                'String', '', 'Enable', 'inactive', 'Tag', 'readonly', 'Position', [5.3*(uis+uil) uiy 0.75*uil 0.7*uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_edit);
uiy = uiy - 0.5*uih - uis;
                    uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'left',...
                                'String', t('Power Vector (M, J0, J45) [D]:'),  'Position', [uis uiy-0.3*uih 3*uil uih-uis],...
                                'FontSize', ui_figures.fontsize_text);
ui_rx_M =           uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'edit', 'Units', 'normalized',...
                                'String', '', 'Enable', 'inactive', 'Tag', 'readonly', 'Position', [3.9*(uis+uil) uiy 0.75*uil 0.7*uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_edit);
ui_rx_J0 =          uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'edit', 'Units', 'normalized',...
                                'String', '', 'Enable', 'inactive', 'Tag', 'readonly', 'Position', [4.6*(uis+uil) uiy 0.75*uil 0.7*uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_edit);
ui_rx_J45 =         uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'edit', 'Units', 'normalized',...
                                'String', '', 'Enable', 'inactive', 'Tag', 'readonly', 'Position', [5.3*(uis+uil) uiy 0.75*uil 0.7*uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_edit);
                            
uiy = uiy - 0.5*uih;                           
uip_zernike_bars =  uipanel(    'Parent', uitab_ophtalmic, 'Title', 'Zernike Coefficients Bar Graph',...
                                'Units', 'normalized', 'FontSize', ui_figures.fontsize_panel,...
                                'Position', [uis 0.15 1-2*uis uiy-0.15]);

% aligned to the bottom
icon = imread('update.png');
                    uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'text', 'Units', 'normalized', 'HorizontalAlignment', 'center',...
                                'String', t('Update'), 'Position', [1-uis-0.15 2*uis+0.6*uih 0.15 0.5*uih],...
                                'FontSize', ui_figures.fontsize_text);
ui_calc_opthalmic = uicontrol(  'Parent', uitab_ophtalmic, 'Style', 'PushButton', 'Units', 'normalized', 'HorizontalAlignment', 'right',...
                                'String', '', 'cdata', icon, 'Position', [1-uis-0.15 uis 0.15 uih],...
                                'FontSize', ui_figures.fontsize_text, 'BackgroundColor', ui_figures.bg_green);